server:
  port: 8081

spring:

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/klovers
    username: anan2
    password: kuaile2515!


redis:
  host: localhost
  port: 6379

front_domain: localhost

